version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "8080:80"
    networks:
      - app-network
  db:
    image: sqlite
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
